version: '3'
services:
    python:
        build: ./docker/python
        container_name: python
        volumes:
            - ./src/:/var/www/html/
        ports:
            - "8080:8000"
        tty: true
